# Copyright 2026 Stanislav Burundukov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Integration and unit tests for simplified active domains selection configuration."""

from __future__ import annotations

import sys

from pathlib import Path

import pytest
import yaml

from entsoe_pipeline import (
    MY_ENTSOE_DOMAINS_CUSTOM_DIR,
    MY_ENTSOE_DOMAINS_EXAMPLES_DIR,
    MY_ENTSOE_DOMAINS_YML,
    CustomConfig,
)
from entsoe_pipeline.fms_metadata.ingestion.my_entsoe_domains import (
    generate_my_entsoe_domains,
)


@pytest.fixture(autouse=True)
def mock_my_entsoe_domains_path(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> Path:
    """Isolates MY_ENTSOE_DOMAINS_YML output paths per parallel worker using tmp_path."""
    mock_file = tmp_path / "my_entsoe_domains.yml"
    monkeypatch.setattr(
        "entsoe_pipeline.fms_metadata.ingestion.my_entsoe_domains.MY_ENTSOE_DOMAINS_YML",
        mock_file,
    )
    monkeypatch.setattr(sys.modules[__name__], "MY_ENTSOE_DOMAINS_YML", mock_file)
    return mock_file


def test_generate_default_domains(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Verifies generation under 'Default' mode using fallback or default template.

    Arrange: Set mock config for Default mode.
    Act: Run generation script.
    Assert: Check output checklist exists and contains IOP/Prod with load active.
    """
    # Arrange
    mock_config = CustomConfig(active_mode="Default")
    monkeypatch.setattr(
        "entsoe_pipeline.fms_metadata.ingestion.my_entsoe_domains.get_custom_config",
        lambda: mock_config,
    )

    # Write a mocked default template file to be independent of developer physical overrides
    mock_template = tmp_path / "mock_my_entsoe_default.yml"
    mock_template.write_text(
        "selected_domains:\n  Load:\n    - ActualTotalLoad_6.1.A_r3\n", encoding="utf-8"
    )
    monkeypatch.setattr(
        "entsoe_pipeline.fms_metadata.ingestion.my_entsoe_domains.MY_ENTSOE_DOMAINS_DEFAULT_TEMPLATE_YML",
        mock_template,
    )

    # Clean previous run artifact if any
    if MY_ENTSOE_DOMAINS_YML.exists():
        MY_ENTSOE_DOMAINS_YML.unlink()

    # Act
    generate_my_entsoe_domains()

    # Assert
    assert MY_ENTSOE_DOMAINS_YML.exists(), (
        f"Resulting domains config was not created at {MY_ENTSOE_DOMAINS_YML}"
    )

    with MY_ENTSOE_DOMAINS_YML.open(encoding="utf-8") as f:
        content = f.read()
        f.seek(0)
        data = yaml.safe_load(f) or {}

    assert "WARNING: THIS FILE IS AUTOMATICALLY GENERATED" in content
    assert "environments" in data

    environments = data["environments"]
    assert "IOP" in environments
    assert "Prod" in environments

    # Check popular domain (Load -> ActualTotalLoad_6.1.A_r3) is enabled (True)
    iop_root_dirs = environments["IOP"]["root_directories"]
    tp_export = next(d for d in iop_root_dirs if d["name"] == "TP_export")
    assert tp_export["domains"]["Load"]["ActualTotalLoad_6.1.A_r3"] is True


def test_generate_example_popular_domains(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Verifies generation under 'Example' mode using 'entsoe_popular_domains'.

    Arrange: Set mock config targeting popular domains example.
    Act: Run generation script.
    Assert: Check that popular domains are built correctly.
    """
    # Arrange
    config_name = "entsoe_popular_domains"
    mock_config = CustomConfig(active_mode="Example", config_name=config_name)
    monkeypatch.setattr(
        "entsoe_pipeline.fms_metadata.ingestion.my_entsoe_domains.get_custom_config",
        lambda: mock_config,
    )

    MY_ENTSOE_DOMAINS_EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)
    temp_popular_file = MY_ENTSOE_DOMAINS_EXAMPLES_DIR / f"{config_name}.yml"

    popular_data = {"popular_domains": {"Load": ["ActualTotalLoad_6.1.A_r3"]}}

    with temp_popular_file.open("w", encoding="utf-8") as f:
        yaml.dump(popular_data, f)

    try:
        # Act
        generate_my_entsoe_domains()

        # Assert
        assert MY_ENTSOE_DOMAINS_YML.exists()
        with MY_ENTSOE_DOMAINS_YML.open(encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}

        environments = data["environments"]
        iop_root_dirs = environments["IOP"]["root_directories"]
        tp_export = next(d for d in iop_root_dirs if d["name"] == "TP_export")

        # Load is a popular domain, should have popular subfolders enabled
        assert tp_export["domains"]["Load"]["ActualTotalLoad_6.1.A_r3"] is True
        # Non-popular should be disabled (False)
        assert (
            tp_export["domains"]["Load"].get("ProductionAndGenerationUnits_r3", False)
            is False
        )
    finally:
        if temp_popular_file.exists():
            temp_popular_file.unlink()


def test_generate_example_test_landing(monkeypatch: pytest.MonkeyPatch) -> None:
    """Verifies generation under 'Example' mode using 'entsoe_test_landing'.

    Arrange: Set mock config targeting entsoe_test_landing example.
    Act: Run generation script.
    Assert: Check that custom domains (Load, Gen, Trans) are enabled.
    """
    # Arrange
    mock_config = CustomConfig(active_mode="Example", config_name="entsoe_test_landing")
    monkeypatch.setattr(
        "entsoe_pipeline.fms_metadata.ingestion.my_entsoe_domains.get_custom_config",
        lambda: mock_config,
    )

    # Act
    generate_my_entsoe_domains()

    # Assert
    assert MY_ENTSOE_DOMAINS_YML.exists()
    with MY_ENTSOE_DOMAINS_YML.open(encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}

    environments = data["environments"]
    iop_root_dirs = environments["IOP"]["root_directories"]
    tp_export = next(d for d in iop_root_dirs if d["name"] == "TP_export")

    # For selected_domains configuration, entire chosen domains are enabled
    expected_val = ["2026_04_ActualTotalLoad_6.1.A_r3.csv"]
    assert tp_export["domains"]["Load"]["ActualTotalLoad_6.1.A_r3"] == expected_val
    assert (
        tp_export["domains"]["Generation"]["ProductionAndGenerationUnits_r3"] is False
    )

    # Balancing domain was not selected, so it should be disabled (False)
    assert tp_export["domains"]["Balancing"]["CurrentBalancingState_12.3.A_r3"] is False


def test_generate_custom_fully_built_config(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Verifies that pre-built checklist templates copy directly with warnings.

    Arrange: Create a temporary custom configuration file.
    Act: Run generation script.
    Assert: Verify the file is written exactly as supplied.
    """
    # Arrange
    config_name = "test_prebuilt_custom"
    mock_config = CustomConfig(active_mode="Custom", config_name=config_name)
    monkeypatch.setattr(
        "entsoe_pipeline.fms_metadata.ingestion.my_entsoe_domains.get_custom_config",
        lambda: mock_config,
    )

    MY_ENTSOE_DOMAINS_CUSTOM_DIR.mkdir(parents=True, exist_ok=True)
    custom_file = MY_ENTSOE_DOMAINS_CUSTOM_DIR / f"{config_name}.yml"

    prebuilt_data = {
        "environments": {
            "IOP": {
                "root_directories": [
                    {
                        "name": "TP_export",
                        "domains": {"Load": {"ActualTotalLoad_6.1.A_r3": True}},
                    }
                ]
            }
        }
    }

    with custom_file.open("w", encoding="utf-8") as f:
        yaml.dump(prebuilt_data, f)

    try:
        # Act
        generate_my_entsoe_domains()

        # Assert
        assert MY_ENTSOE_DOMAINS_YML.exists()
        with MY_ENTSOE_DOMAINS_YML.open(encoding="utf-8") as f:
            content = f.read()
            f.seek(0)
            data = yaml.safe_load(f) or {}

        assert "WARNING: THIS FILE IS AUTOMATICALLY GENERATED" in content
        data.pop("generated_at", None)
        assert data == prebuilt_data

    finally:
        # Clean up temporary test custom file
        if custom_file.exists():
            custom_file.unlink()


def test_unrecognized_config_errors(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Verifies that invalid configuration formats raise explicit ValueErrors.

    Arrange: Create an invalid custom configuration file and mock overview.yml.
    Act / Assert: Verify ValueError is raised.
    """
    # Arrange
    config_name = "test_invalid"
    mock_config = CustomConfig(active_mode="Custom", config_name=config_name)
    monkeypatch.setattr(
        "entsoe_pipeline.fms_metadata.ingestion.my_entsoe_domains.get_custom_config",
        lambda: mock_config,
    )

    MY_ENTSOE_DOMAINS_CUSTOM_DIR.mkdir(parents=True, exist_ok=True)
    custom_file = MY_ENTSOE_DOMAINS_CUSTOM_DIR / f"{config_name}.yml"

    invalid_data = {"unrecognized_key": "some_value"}

    with custom_file.open("w", encoding="utf-8") as f:
        yaml.dump(invalid_data, f)

    mock_overview = tmp_path / "overview.yml"
    with mock_overview.open("w", encoding="utf-8") as f:
        yaml.dump({"environments": {"IOP": {"root_directories": []}}}, f)

    monkeypatch.setattr(
        "entsoe_pipeline.fms_metadata.ingestion.my_entsoe_domains.OVERVIEW_YML",
        mock_overview,
    )

    try:
        # Act & Assert
        with pytest.raises(ValueError, match="Invalid checklist template"):
            generate_my_entsoe_domains()
    finally:
        if custom_file.exists():
            custom_file.unlink()
