# Copyright 2026 Stanislav Burundukov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""JSON Metadata Observability and Serialization Facade."""

from __future__ import annotations

import json
import sys

from pathlib import Path
from typing import Any

from entsoe_pipeline.config.paths import PROJECT_ROOT
from entsoe_pipeline.logger.core.generated_at import get_generated_at_timestamp


def save_json_with_observability(
    output_path: Path,
    payload: Any,
    generator_script_name: str | None = None,
    sort_keys: bool = True,
) -> None:
    """Serializes a payload to JSON with warning metadata and execution timestamp.

    Args:
        output_path: Target filesystem Path to write.
        payload: Structured payload (normally a dictionary).
        generator_script_name: The name/path of the generating script.
          If None, resolves relative to PROJECT_ROOT using sys.argv[0].
        sort_keys: Whether to sort keys alphabetically.
    """
    # 1. Resolve generator script name
    if not generator_script_name:
        main_script = Path(sys.argv[0]).resolve()
        try:
            generator_script_name = str(main_script.relative_to(PROJECT_ROOT))
        except ValueError:
            generator_script_name = main_script.name

    # 2. Inject generated_at and warning metadata at the top of mapping payload
    if isinstance(payload, dict):
        ordered_payload = {
            "_warning": (
                "WARNING: THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY. "
                f"Generated by: {generator_script_name}."
            ),
            "_generated_at": get_generated_at_timestamp(),
        }
        for k, v in payload.items():
            if k not in ("_warning", "_generated_at"):
                ordered_payload[k] = v
        payload = ordered_payload

    # 3. Serialize using json.dump
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=sort_keys)
