services:
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    restart: unless-stopped

    ports:
      - "${MASTER_HTTP_PORT:-9333}:9333" # Master HTTP (Admin UI)
      - "${MASTER_GRPC_PORT:-19333}:19333" # Master gRPC
      - "${VOLUME_HTTP_PORT:-8080}:8080" # Volume Server HTTP
      - "${FILER_HTTP_PORT:-8888}:8888" # Filer HTTP
      - "${FILER_GRPC_PORT:-18888}:18888" # Filer gRPC
      - "${S3_COMPATIBLE_PORT:-8333}:8333" # S3 API Gateway
      - "${ICEBERG_CATALOG_PORT:-8181}:8181" # Built-in Iceberg REST Catalog

    environment:
      - S3_LANDING_BUCKET=${S3_LANDING_BUCKET}
      - S3_LAKEHOUSE_BUCKET=${S3_LAKEHOUSE_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    volumes:
      - ${S3_COMPATIBLE_VOLUME:-/mnt/seaweed_data}:/data
