datasources:
  postgres:
    url: jdbc:postgresql://kestra_postgres:5432/kestra
    driverClassName: org.postgresql.Driver
    username: kestra
    password: ${KESTRA_DB_PASSWORD}

kestra:
  server:
    basicAuth:
      username: ${KESTRA_USER}
      password: ${KESTRA_PASS}
  repository:
    type: postgres
  storage:
    type: local
    local:
      basePath: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmpDir:
      path: /tmp/kestra-wd/tmp
  url: ${KESTRA_URL:-http://localhost:8082/}
  plugins:
    configurations:
      - type: io.kestra.plugin.scripts.runner.docker.Docker
        values:
          volume-enabled: true
