# Copyright 2026 Stanislav Burundukov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generates standard warnings to be inserted into machine-generated files."""

from __future__ import annotations


def get_yaml_warning(generator_script_name: str) -> str:
    """Returns a standard YAML warning comment header.

    Args:
        generator_script_name: The name/path of the script generating the file.

    Returns:
        str: A formatted warning string.
    """
    return (
        "# =====================================================================\n"
        "# WARNING: THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.\n"
        f"# Generated by: {generator_script_name}\n"
        "# =====================================================================\n\n"
    )


def get_my_entsoe_domains_warning(generator_script_name: str) -> str:
    """Returns a specific YAML warning header for my_entsoe_domains configs.

    Args:
        generator_script_name: The name/path of the script generating the file.

    Returns:
        str: A formatted warning string with guidance on customization.
    """
    return (
        "# =====================================================================\n"
        "# WARNING: THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.\n"
        f"# Generated by: {generator_script_name}\n"
        "#\n"
        "# To customize, please edit active_mode and config_name in:\n"
        "# config_env/my_entsoe_domains.yml\n"
        "#\n"
        "# You can place your custom YAML files under:\n"
        "# config/domains/custom/\n"
        "# =====================================================================\n\n"
    )
