# =====================================================================
# INSTRUCTION TO RUN DOMAIN CONFIGURATION FOR LANDING ZONE PIPELINE
#
# This is an example of a machine generated domain configuration for landing zone pipeline.
# To generate your own please do the folowing:
#
# 1. Complete config_env/my_entsoe_domains.yml
# (by default it will use popular domains listed at config/domains/default/my_entsoe_default.yml)
# to see the example visit config_env_example/my_entsoe_domains.yml
#
# 2. run `just generate-my-entsoe-domains` command
# to generate config/domains/my_entsoe_domains.yml
# (this file)
#
# 3. Now you can run `just ingest_my_entsoe_domains` command to ingest the data
# in S3 compatible storage
#
# NOTE: by defaul your actual config/domains/my_entsoe_domains.yml will not exist.
#   you will need to create it based on that instruction above.
#   You may also want to simply use the default configuration:
#     - my_entsoe_default.yml
#   or example configurations:
#     - entsoe_popular_domains.yml
#     - entsoe_test_landing.yml
#   or create your own custom configuration at config/domains/custom/ folder!
# 
# EXAMPLE IS BELOW THIS LINE:
# =====================================================================

# =====================================================================
# WARNING: THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.
# Generated by: src/entsoe_pipeline/fms_metadata/ingestion/my_entsoe_domains.py
#
# To customize, please edit active_mode and config_name in:
# config_env/my_entsoe_domains.yml
#
# You can place your custom YAML files under:
# config/domains/custom/
# =====================================================================

environments:
  IOP:
    root_directories:
    - name: TP_export
      domains:
        Load:
          ActualTotalLoad_6.1.A_r3:
          - 2026_04_ActualTotalLoad_6.1.A_r3.csv
          DayAheadTotalLoadForecast_6.1.B_r3: false
          TotalLoadForecast_6.1.C_D_E_r3: false
        Generation:
          ActualGenerationOutputPerGenerationUnit_16.1.A_r3:
          - 2026_04_ActualGenerationOutputPerGenerationUnit_16.1.A_r3.csv
          AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D_r3: false
          AggregatedGenerationPerType_16.1.B_C_r3: false
          DayAheadAggregatedGeneration_14.1.C_r3: false
          GenerationForecastsForWindAndSolar_14.1.D_r3: false
          InstalledGenerationCapacityPerProductionUnit_14.1.B_r3: false
          ProductionAndGenerationUnits_r3: false
        Transmission:
          CommercialSchedulesNetPositions_12.1.F_r3:
          - 2026_04_CommercialSchedulesNetPositions_12.1.F_r3.csv
          CommercialSchedules_12.1.F_r3: false
          CrossBorderCapacityForDCLinksRampingRestrictions_11.3_r3: false
          CrossBorderCapacityForDcLinksIntradayTransferLimits_11.3_r3: false
          FlowBasedAllocationsCongestionIncome_12.1.E_r3: false
          FlowBasedCapacityAllocation_11.1.B_r3: false
          ForecastedTransferCapacities_11.1_r3: false
          ImplicitAllocationsCongestionIncome_12.1.E_r3: false
          ImplicitAllocationsNetPositions_12.1.E_r3: false
          OfferedTransferCapacitiesContinuousEvolution_11.1_r3: false
          OfferedTransferCapacitiesContinuous_11.1_r3: false
          OfferedTransferCapacitiesExplicit_11.1_r3: false
          OfferedTransferCapacitiesImplicit_11.1_r3: false
          PhysicalFlows_12.1.G_r3: false
          PowerTransferDistributionFactors_11.1.B_r3: false
          TotalCapacityAlreadyAllocated_12.1.C_r3: false
          TotalCapacityNominated_12.1.B_r3: false
          TransferCapacitiesAllocatedWithThirdCountries_12.1.H_r3: false
          TransmissionAssets_r3: false
          TransmissionAssets_r3.1: false
          UseOfTransferCapacity_12.1.A_r3: false
        Balancing:
          AggregatedBalancingEnergyBids_12.3.E_r3: false
          AmountAndPricesPaidOfBalancingReservesUnderContract_17.1.B_C_r3: false
          BalancingBorderCapacityLimitations_IFs_4.3_4.4_r3: false
          BalancingEnergyBidsArchives_12.3.B_C_r3: false
          BalancingEnergyBids_12.3.B_C_r3: false
          ChangesToBidAvailabilityArchives_IFs_mFRR9.9_aFRR9.6_9.8_r3: false
          ChangesToBidAvailability_IFs_mFRR9.9_aFRR9.6_9.8_r3: false
          CrossZonalBalancingCapacity_12.3.H_12.3.I_r3: false
          CurrentBalancingState_12.3.A_r3: false
          ElasticDemands_IFs_mFRR3.4_aFRR3.4_r3: false
          Fallbacks_IF_IN7.2_mFRR3.11_aFRR3.10_r3: false
          FinancialExpensesAndIncomeForBalancing_17.1.I_r3: false
          ImbalancePrices_17.1.G_r3: false
          NettedAndExchangedVolumesPerBorder_IFs_IN3.10_mFRR3.17_r3: false
          NettedAndExchangedVolumes_IFs_IN3.10_mFRR3.17_r3: false
          PricesOfActivatedBalancingEnergy_17.1.F_r3: false
          ProcuredBalancingCapacity_12.3.F_r3: false
          ProcuredBalancingCapacity_12.3.F_r3.1: false
          TotalImbalanceVolumes_17.1.H_r3: false
        Market:
          AuctionRevenue_12.1.A_r3: false
          CostsOfCongestionManagement_13.1.C_r3: false
          EnergyPrices_12.1.D_r3: false
          ExpansionAndDismantlingProjectsReport_9.1_r3: false
          ExpansionAndDismantlingProjects_9.1_r3: false
        Outages:
          UnavailabilityInTheTransmissionGridAffectedAreas_10.1.A_B_r3: false
          UnavailabilityInTheTransmissionGridAffectedAssets_10.1.A_B_r3: false
          UnavailabilityInTheTransmissionGrid_10.1.A_B_r3: false
          UnavailabilityOfConsumptionUnits_7.1.A_B_r3: false
          UnavailabilityOfOffshoreGrid_10.1.C_r3: false
          UnavailabilityOfProductionAndGenerationUnits_15.1.A_B_C_D_r3: false
        Operations:
          ActualCapacitiesAndOutlookOnFrequencyRestorationReserveAndReplacementReserve_SOGL_188.3_188.4_189.2_189.3_r3: false
          Algorithm_12.3.K_r3: false
          ApprovedMethodologies_12.3.J_r3: false
          CommonAnnualReport_12.3.L_r3: false
          Countertrading_13.1.B_r3: false
          Countertrading_13.1.B_r3.1: false
          CrossBorderMarginalPriceForAfrrCs_IF_aFRR3.16_r3: false
          ExchangedVolumesAndPricesProvidedByActivationOptimisationFunction_IFs_aFRR3.16_r3: false
          PermanentAllocationLimitations_IFs_4.5_r3: false
          RedispatchingCrossBorder_13.1.A_r3: false
          RedispatchingCrossBorder_13.1.A_r3.1: false
          RedispatchingInternal_13.1.A_r3: false
          RedispatchingInternal_13.1.A_r3.1: false
          ResultsOfTheCriteriaApplicationProcess_SOGL_185.4_r3: false
        OtherMarketInformation:
          Export_log_r3.csv: false
          Export_oce_log_r3.csv: false
          OtherMarketInformation_r3: false
          OtherMarketInformation_r3.1: false
    - name: TP_Legacy_Publications
      folders:
        BalanceManagementCsv_r1: false
        BalanceManagementXlsx_r1: false
        BalanceManagementXml_r1: false
        CrossBorderCommercialSchedulesCsv_r1: false
        CrossBorderCommercialSchedulesXml_r1: false
        CrossBorderPhysicalFlowsCsv_r1: false
        CrossBorderPhysicalFlowsXml_r1: false
        DailyExplicitAuctionCsv_r1: false
        DailyExplicitAuctionXml_r1: false
        DailyImplicitAuctionCsv_r1: false
        DailyImplicitAuctionXml_r1: false
        DayAheadNetTransferCapacitiesCsv_r1: false
        DayAheadNetTransferCapacitiesXml_r1: false
        ExchangeReserveCapacity_SOGL_190.3_r2: false
        ExchangedReserveCapacity_SOGL_190.3_r2: false
        FlowBasedCapacityAllocationArchives_11.1.B_r3: false
        FrequencyRestorationReserveCapacityForecast_SOGL_188.3_r2: false
        ImbalancePricesArchives_17.1.G_r3: false
        MonthAheadNetTransferCapacitiesCsv_r1: false
        MonthAheadNetTransferCapacitiesXml_r1: false
        MonthlyExplicitAuctionCsv_r1: false
        MonthlyExplicitAuctionXml_r1: false
        OutagesCsv_r1: false
        OutagesXml_r1: false
        PlannedScheduleEvolutionCsv_r1: false
        PlannedScheduleEvolutionXml_r1: false
        QuarterlyExplicitAuctionCsv_r1: false
        QuarterlyExplicitAuctionXml_r1: false
        ReplacementReserveCapacityForecast_SOGL_189.2_r2: false
        RulesOnBalancing_17.1.A_r2: false
        SemestrialExplicitAuctionCsv_r1: false
        SemestrialExplicitAuctionXml_r1: false
        SharingOfFrequencyContainmentReserve_SOGL_190.2_r2: false
        SystemVerticalLoadCsv_r1: false
        SystemVerticalLoadXml_r1: false
        TotalLoadCsv_r1: false
        TotalLoadXml_r1: false
        ValuesOfFrequencyQualityEvaluations_SOGL_185.2_r2: false
        WeekAheadNetTransferCapacitiesCsv_r1: false
        WeekAheadNetTransferCapacitiesXml_r1: false
        WeekendExplicitAuctionCsv_r1: false
        WeekendExplicitAuctionXml_r1: false
        YearAheadNetTransferCapacitiesCsv_r1: false
        YearAheadNetTransferCapacitiesXml_r1: false
        YearlyExplicitAuctionCsv_r1: false
        YearlyExplicitAuctionXml_r1: false
  Prod:
    root_directories:
    - name: TP_export
      domains:
        Load:
          ActualTotalLoad_6.1.A_r3: false
          DayAheadTotalLoadForecast_6.1.B_r3: false
          TotalLoadForecast_6.1.C_D_E_r3: false
          YearAheadForecastMargin_8.1_r3: false
        Generation:
          ActualGenerationOutputPerGenerationUnit_16.1.A_r3: false
          AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D_r3: false
          AggregatedGenerationPerType_16.1.B_C_r3: false
          DayAheadAggregatedGeneration_14.1.C_r3: false
          GenerationForecastsForWindAndSolar_14.1.D_r3: false
          InstalledGenerationCapacityAggregated_14.1.A_r3: false
          InstalledGenerationCapacityPerProductionUnit_14.1.B_r3: false
          ProductionAndGenerationUnits_r3: false
        Transmission:
          CommercialSchedulesNetPositions_12.1.F_r3: false
          CommercialSchedules_12.1.F_r3: false
          CrossBorderCapacityForDCLinksRampingRestrictions_11.3_r3: false
          CrossBorderCapacityForDcLinksIntradayTransferLimits_11.3_r3: false
          FlowBasedAllocationsCongestionIncome_12.1.E_r3: false
          ForecastedTransferCapacities_11.1_r3: false
          ImplicitAllocationsCongestionIncome_12.1.E_r3: false
          ImplicitAllocationsNetPositions_12.1.E_r3: false
          OfferedTransferCapacitiesContinuousEvolution_11.1_r3: false
          OfferedTransferCapacitiesContinuous_11.1_r3: false
          OfferedTransferCapacitiesExplicit_11.1_r3: false
          OfferedTransferCapacitiesImplicit_11.1_r3: false
          PhysicalFlows_12.1.G_r3: false
          TotalCapacityAlreadyAllocated_12.1.C_r3: false
          TotalCapacityNominated_12.1.B_r3: false
          TransferCapacitiesAllocatedWithThirdCountries_12.1.H_r3: false
          TransmissionAssets_r3: false
          TransmissionAssets_r3.1: false
          UseOfTransferCapacity_12.1.A_r3: false
        Balancing:
          AggregatedBalancingEnergyBids_12.3.E_r3: false
          AmountAndPricesPaidOfBalancingReservesUnderContract_17.1.B_C_r3: false
          BalancingBorderCapacityLimitations_IFs_4.3_4.4_r3: false
          BalancingEnergyBidsArchives_12.3.B_C_r3: false
          BalancingEnergyBids_12.3.B_C_r3: false
          ChangesToBidAvailabilityArchives_IFs_mFRR9.9_aFRR9.6_9.8_r3: false
          ChangesToBidAvailability_IFs_mFRR9.9_aFRR9.6_9.8_r3: false
          CrossZonalBalancingCapacity_12.3.H_12.3.I_r3: false
          CurrentBalancingState_12.3.A_r3: false
          ElasticDemands_IFs_mFRR3.4_aFRR3.4_r3: false
          Fallbacks_IF_IN7.2_mFRR3.11_aFRR3.10_r3: false
          FinancialExpensesAndIncomeForBalancing_17.1.I_r3: false
          ImbalancePrices_17.1.G_r3: false
          NettedAndExchangedVolumesAfrr_IFs_aFRR3.16_r3: false
          NettedAndExchangedVolumesPerBorder_IFs_IN3.10_mFRR3.17_r3: false
          NettedAndExchangedVolumes_IFs_IN3.10_mFRR3.17_r3: false
          PricesOfActivatedBalancingEnergy_17.1.F_r3: false
          ProcuredBalancingCapacity_12.3.F_r3: false
          TotalImbalanceVolumes_17.1.H_r3: false
        Market:
          AuctionRevenue_12.1.A_r3: false
          CostsOfCongestionManagement_13.1.C_r3: false
          EnergyPrices_12.1.D_r3: false
          ExpansionAndDismantlingProjectsReport_9.1_r3: false
          ExpansionAndDismantlingProjects_9.1_r3: false
        Outages:
          UnavailabilityInTheTransmissionGrid_10.1.A_B_r3: false
          UnavailabilityOfConsumptionUnits_7.1.A_B_r3: false
          UnavailabilityOfOffshoreGrid_10.1.C_r3: false
          UnavailabilityOfProductionAndGenerationUnits_15.1.A_B_C_D_r3: false
        Operations:
          ActualCapacitiesAndOutlookOnFrequencyRestorationReserveAndReplacementReserve_SOGL_188.3_188.4_189.2_189.3_r3: false
          Algorithm_12.3.K_r3: false
          ApprovedMethodologies_12.3.J_r3: false
          CommonAnnualReport_12.3.L_r3: false
          Countertrading_13.1.B_r3.1: false
          CrossBorderMarginalPriceForAfrrCs_IF_aFRR3.16_r3: false
          ExchangedReserveCapacity_SOGL_190.3_r3: false
          FrequencyContainmentReserveAmountAndShares_SOGL_187.2_r3: false
          PermanentAllocationLimitations_IFs_4.5_r3: false
          RedispatchingCrossBorder_13.1.A_r3.1: false
          RedispatchingInternal_13.1.A_r3.1: false
          ResultsOfTheCriteriaApplicationProcess_SOGL_185.4_r3: false
        OtherMarketInformation:
          Export_log_r3.csv: false
          Export_oce_log_r3.csv: false
          OtherMarketInformation_r3.1: false
    - name: TP_Legacy_Publications
      folders:
        AcceptedAggregatedOffers_17.1.D_r2: false
        ActivatedBalancingEnergy_17.1.E_r2: false
        BalanceManagementCsv_R1: false
        BalanceManagementXml_r1: false
        CrossBorderBalancingEnergyActivated_17.1.J_r2: false
        CrossBorderBalancingPrices_17.1.J_r2: false
        CrossBorderBalancingVolumesOfExchangedBidsAndOffers_17.1.J_r2: false
        CrossBorderCommercialSchedulesCsv_r1: false
        CrossBorderCommercialSchedulesXml_r1: false
        CrossBorderPhysicalFlowsCsv_r1: false
        CrossBorderPhysicalFlowsXml_r1: false
        DailyExplicitAuctionCsv_r1: false
        DailyExplicitAuctionXml_r1: false
        DailyImplicitAuctionCsv_r1: false
        DailyImplicitAuctionXml_r1: false
        DayAheadNetTransferCapacitiesCsv_r1: false
        DayAheadNetTransferCapacitiesXml_r1: false
        ExchangedReserveCapacity_SOGL_190.3_r2: false
        FcrTotalCapacity_187.2_r2: false
        FinancialExpensesAndIncomeForBalancing_17.1.I_r2: false
        FlowBasedCapacityAllocationArchives_11.1.B_r3: false
        FrequencyRestorationReserveCapacityForecast_SOGL_188.3_r2: false
        FrrActualCapacity_188.4_r2: false
        ImbalancePricesArchives_17.1.G_r3: false
        MonthAheadNetTransferCapacitiesCsv_r1: false
        MonthAheadNetTransferCapacitiesXml_r1: false
        MonthlyExplicitAuctionCsv_r1: false
        MonthlyExplicitAuctionXml_r1: false
        OutagesCsv_r1: false
        OutagesXml_r1: false
        PlannedScheduleEvolutionCsv_r1: false
        PlannedScheduleEvolutionXml_r1: false
        QuarterlyExplicitAuctionCsv_r1: false
        QuarterlyExplicitAuctionXml_r1: false
        Redispatching_13.1.A_r2: false
        ReplacementReserveCapacityForecast_SOGL_189.2_r2: false
        RrActualCapacity_189.3_r2: false
        RulesOnBalancing_17.1.A_r2: false
        SemestrialExplicitAuctionCsv_r1: false
        SemestrialExplicitAuctionXml_r1: false
        SharesOfFcrCapacity_187.2_r2: false
        SharingOfFrequencyContainmentReserve_SOGL_190.2_r2: false
        SystemVerticalLoadCsv_r1: false
        SystemVerticalLoadXml_r1: false
        TotalCapacityNominatedArchives_12.1.B_r3: false
        TotalLoadCsv_r1: false
        TotalLoadXml_r1: false
        TransferCapacitiesAllocatedWithThirdCountriesDailyImplicit_12.1.H_r2: false
        ValuesOfFrequencyQualityEvaluations_SOGL_185.2_r2: false
        WeekAheadNetTransferCapacitiesCsv_r1: false
        WeekAheadNetTransferCapacitiesXml_r1: false
        WeekendExplicitAuctionCsv_r1: false
        WeekendExplicitAuctionXml_r1: false
        YearAheadNetTransferCapacitiesCsv_r1: false
        YearAheadNetTransferCapacitiesXml_r1: false
        YearlyExplicitAuctionCsv_r1: false
        YearlyExplicitAuctionXml_r1: false
